{
  "openapi": "3.1.0",
  "info": {
    "version": "2.2.0",
    "title": "Task Pro API",
    "description": "The Task Pro API provides endpoints to manage projects and user assignments, ensuring secure and efficient request handling.",
    "contact": {
      "name": "TaskPro",
      "url": "https://www.taskpro.online"
    }
  },
  "servers": [
    { "url": "http://localhost:8000/api - Development" },
    { "url": "https://api.taskpro.online - Production" }
  ],
  "paths": {
    "/auth/signup": {
      "post": {
        "tags": ["Auth"],
        "summary": "Create a new user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "name": "John Doe",
                "email": "user@example.com",
                "password": "qwerty123"
              }
            }
          }
        },
        "responses": {
          "201": { "$ref": "#/components/responses/AuthResponse" },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 400,
                  "message": {
                    "email": "Email is invalid",
                    "password": "Password must be at least 8 characters",
                    "name": "Name must be at least 2 characters"
                  }
                }
              }
            }
          },
          "409": { "$ref": "#/components/responses/Conflict" }
        }
      }
    },
    "/auth/signin": {
      "post": {
        "tags": ["Auth"],
        "summary": "Signin a user",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "email": "user@example.com",
                "password": "qwerty123"
              }
            }
          }
        },
        "responses": {
          "201": { "$ref": "#/components/responses/AuthResponse" },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 400,
                  "message": {
                    "email": "Email is invalid",
                    "password": "Password must be at least 8 characters"
                  }
                }
              }
            }
          },
          "401": {
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 401,
                  "message": "Email or password invalid"
                }
              }
            }
          }
        }
      }
    },
    "/auth/google": {
      "post": {
        "tags": ["Auth"],
        "summary": "Signin a user with google",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "code": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzE3NDNkYjg1Yzk2NDUzZTA0YTY4NCIsInNpZCI6IjY2NzE3OWE0YTgxZmI1MjIzOTg0NmY2MSIsImlhdCI6MTcxODcxMjc0MCwiZXhwIjoxNzE5MzE3NTQwfQ.B8htZY5kU0kvX2UYsEN0u7ZUPVxTKfCs5ASAocTc-P4"
              }
            }
          }
        },
        "responses": {
          "201": { "$ref": "#/components/responses/GoogleResponse" },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 400,
                  "message": {
                    "code": "Code must be a string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/tokens": {
      "post": {
        "tags": ["Auth"],
        "summary": "Get new access and refresh tokens",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzE3NDNkYjg1Yzk2NDUzZTA0YTY4NCIsInNpZCI6IjY2NzE3OWE0YTgxZmI1MjIzOTg0NmY2MSIsImlhdCI6MTcxODcxMjc0MCwiZXhwIjoxNzE5MzE3NTQwfQ.B8htZY5kU0kvX2UYsEN0u7ZUPVxTKfCs5ASAocTc-P4"
              }
            }
          }
        },
        "responses": {
          "200": { "$ref": "#/components/responses/TokensResponse" },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 400,
                  "message": {
                    "refreshToken": "refreshToken must be a string"
                  }
                }
              }
            }
          },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "403": {
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 403,
                  "message": "Forbidden"
                }
              }
            }
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "Logout a user",
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": { "$ref": "#/components/responses/NoContent" },
          "401": { "$ref": "#/components/responses/Unauthorized" }
        }
      }
    },
    "/user/me": {
      "get": {
        "tags": ["User"],
        "summary": "Get current user",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": { "$ref": "#/components/responses/UserResponse" },
          "401": { "$ref": "#/components/responses/Unauthorized" }
        }
      }
    },
    "/user/help": {
      "post": {
        "tags": ["User"],
        "summary": "Send email need help",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": { "email": "user@example.com", "comment": "Need help" }
            }
          }
        },
        "responses": {
          "200": {
            "content": {
              "application/json": { "example": { "message": "Email sent" } }
            }
          },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 400,
                  "message": {
                    "email": "Email is required",
                    "comment": "Comment is required"
                  }
                }
              }
            }
          },
          "401": { "$ref": "#/components/responses/Unauthorized" }
        }
      }
    },
    "/user": {
      "put": {
        "tags": ["User"],
        "summary": "Edit user profile",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": { "example": { "password": "123456789" } },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "avatar": { "type": "string", "format": "binary" }
                }
              }
            }
          }
        },
        "responses": {
          "200": { "$ref": "#/components/responses/UserResponse" },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 400,
                  "message": {
                    "email": "Email is invalid",
                    "name": "Name must be at least 2 characters"
                  }
                }
              }
            }
          },
          "406": {
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 406,
                  "message": "File must have .jpeg or .png extension"
                }
              }
            }
          },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "409": { "$ref": "#/components/responses/Conflict" }
        }
      }
    },
    "/user/theme": {
      "put": {
        "tags": ["User"],
        "summary": "Switch user theme",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": { "example": { "theme": "light" } }
          }
        },
        "responses": {
          "200": { "$ref": "#/components/responses/UserResponse" },
          "400": {
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 400,
                  "errors": {
                    "theme": "Theme must be one of the following: light, dark, violet"
                  }
                }
              }
            }
          },
          "401": { "$ref": "#/components/responses/Unauthorized" }
        }
      }
    },
    "/board": {
      "get": {
        "tags": ["Board"],
        "summary": "Get all boards",
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": { "$ref": "#/components/responses/AllBoardsResponse" },
          "401": { "$ref": "#/components/responses/Unauthorized" }
        }
      },
      "post": {
        "tags": ["Board"],
        "summary": "Add new board",
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "title": "My office",
                "icon": "lightning",
                "background": "blue-ball"
              }
            }
          }
        },
        "responses": {
          "201": { "$ref": "#/components/responses/BoardResponse" },
          "400": { "$ref": "#/components/responses/BoardBadRequest" },
          "401": { "$ref": "#/components/responses/Unauthorized" }
        }
      }
    },
    "/board/{boardId}": {
      "get": {
        "tags": ["Board"],
        "summary": "Get board by id",
        "parameters": [{ "in": "path", "name": "boardId", "required": true }],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": { "$ref": "#/components/responses/BoardByIdResponse" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      },
      "put": {
        "tags": ["Board"],
        "summary": "Edit board by id",
        "parameters": [{ "in": "path", "name": "boardId", "required": true }],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": { "example": { "title": "My office" } }
          }
        },
        "responses": {
          "200": { "$ref": "#/components/responses/BoardResponse" },
          "400": { "$ref": "#/components/responses/BoardBadRequest" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      },
      "delete": {
        "tags": ["Board"],
        "summary": "Delete board by id",
        "parameters": [{ "in": "path", "name": "boardId", "required": true }],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": { "$ref": "#/components/responses/NoContent" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      }
    },
    "/column/{boardId}": {
      "post": {
        "tags": ["Column"],
        "summary": "Add new column",
        "parameters": [{ "in": "path", "name": "boardId", "required": true }],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": { "example": { "title": "In progress" } }
          }
        },
        "responses": {
          "201": { "$ref": "#/components/responses/ColumnResponse" },
          "400": { "$ref": "#/components/responses/ColumnBadRequest" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      }
    },
    "/column/{columnId}": {
      "put": {
        "tags": ["Column"],
        "summary": "Edit column by id",
        "parameters": [{ "in": "path", "name": "columnId", "required": true }],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": { "example": { "title": "In progress" } }
          }
        },
        "responses": {
          "201": { "$ref": "#/components/responses/ColumnResponse" },
          "400": { "$ref": "#/components/responses/ColumnBadRequest" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      },
      "delete": {
        "tags": ["Column"],
        "summary": "Delete column by id",
        "parameters": [{ "in": "path", "name": "columnId", "required": true }],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": { "$ref": "#/components/responses/NoContent" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      }
    },
    "/column/{boardId}/order": {
      "patch": {
        "tags": ["Column"],
        "summary": "Update columns order",
        "parameters": [{ "in": "path", "name": "boardId", "required": true }],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "ids": [
                  "67470731ed1b2ff3a2e5bd56",
                  "67470773c750b6298e1892ad",
                  "67470737ed1b2ff3a2e5bd57"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/UpdateColumnsOrderResponse"
          },
          "400": { "$ref": "#/components/responses/UpdateOrderBadRequest" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      }
    },
    "/card/{columnId}": {
      "post": {
        "tags": ["Card"],
        "summary": "Add new card",
        "parameters": [{ "in": "path", "name": "columnId", "required": true }],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "title": "Publication of the project",
                "description": "Review the project materials: Familiarize yourself with the project's content, including text, images, and any supplementary materials.",
                "deadline": "2025-10-15",
                "priority": "High"
              }
            }
          }
        },
        "responses": {
          "201": { "$ref": "#/components/responses/CardResponse" },
          "400": { "$ref": "#/components/responses/CardBadRequest" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      }
    },
    "/card/{cardId}": {
      "put": {
        "tags": ["Card"],
        "summary": "Edit card by id",
        "parameters": [{ "in": "path", "name": "cardId", "required": true }],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": { "title": "Publication of the project" }
            }
          }
        },
        "responses": {
          "200": { "$ref": "#/components/responses/CardResponse" },
          "400": { "$ref": "#/components/responses/CardBadRequest" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      },
      "delete": {
        "tags": ["Card"],
        "summary": "Delete card by id",
        "parameters": [{ "in": "path", "name": "cardId", "required": true }],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": { "$ref": "#/components/responses/NoContent" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      }
    },
    "/card/{columnId}/order": {
      "patch": {
        "tags": ["Card"],
        "summary": "Update cards order",
        "parameters": [{ "in": "path", "name": "columnId", "required": true }],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "example": {
                "ids": ["6672fdccc07147fc7ae1bb93", "6743474be4006eca6c8122e7"]
              }
            }
          }
        },
        "responses": {
          "200": { "$ref": "#/components/responses/UpdateCardOrderResponse" },
          "400": { "$ref": "#/components/responses/UpdateOrderBadRequest" },
          "401": { "$ref": "#/components/responses/Unauthorized" },
          "404": { "$ref": "#/components/responses/NotFound" }
        }
      }
    }
  },
  "components": {
    "responses": {
      "NotFound": {
        "content": {
          "application/json": {
            "example": { "statusCode": 404, "message": "Not found" }
          }
        }
      },
      "Conflict": {
        "content": {
          "application/json": {
            "example": {
              "statusCode": 409,
              "message": "Provided email already exists"
            }
          }
        }
      },
      "NoContent": {
        "content": {
          "application/json": { "example": { "message": "No content" } }
        }
      },
      "Unauthorized": {
        "content": {
          "application/json": {
            "example": { "statusCode": 401, "message": "Unauthorized" }
          }
        }
      },
      "AuthResponse": {
        "content": {
          "application/json": {
            "example": {
              "user": {
                "id": "674723719b47fd08e6a2d517",
                "name": "John Doe",
                "email": "user@example.com",
                "theme": "light",
                "avatar": "https://res.cloudinary.com/dmbnnewoy/image/upload/v1706958682/TaskPro/user_avatar_default/user_light.png",
                "avatarPublicId": null
              },
              "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDcyMzcxOWI0N2ZkMDhlNmEyZDUxNyIsInNpZCI6IjY3NDcyMzcyOWI0N2ZkMDhlNmEyZDUxOCIsImlhdCI6MTczMjcxNTM3OCwiZXhwIjoxNzMyNzE4OTc4fQ.ZCaaWh4rc4AHzTSljDbc7mq5gbHvjMx54y6LoJsXX-4",
              "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDcyMzcxOWI0N2ZkMDhlNmEyZDUxNyIsInNpZCI6IjY3NDcyMzcyOWI0N2ZkMDhlNmEyZDUxOCIsImlhdCI6MTczMjcxNTM3OCwiZXhwIjoxNzMzMzIwMTc4fQ.y17k3eWBJ4WeqNZeuguOh_5UQDiyaCPYFmn_Ir-Ftog"
            }
          }
        }
      },
      "GoogleResponse": {
        "content": {
          "application/json": {
            "example": {
              "user": {
                "id": "674723719b47fd08e6a2d517",
                "name": "John Doe",
                "email": "user@example.com",
                "theme": "light",
                "avatar": "https://lh3.googleusercontent.com/a/ACg8ocLWRkQo4yOicLduVfTehM7hCPx1Q7WGFjgOFu1GT",
                "avatarPublicId": "google-picture"
              },
              "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDcyMzcxOWI0N2ZkMDhlNmEyZDUxNyIsInNpZCI6IjY3NDcyMzcyOWI0N2ZkMDhlNmEyZDUxOCIsImlhdCI6MTczMjcxNTM3OCwiZXhwIjoxNzMyNzE4OTc4fQ.ZCaaWh4rc4AHzTSljDbc7mq5gbHvjMx54y6LoJsXX-4",
              "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDcyMzcxOWI0N2ZkMDhlNmEyZDUxNyIsInNpZCI6IjY3NDcyMzcyOWI0N2ZkMDhlNmEyZDUxOCIsImlhdCI6MTczMjcxNTM3OCwiZXhwIjoxNzMzMzIwMTc4fQ.y17k3eWBJ4WeqNZeuguOh_5UQDiyaCPYFmn_Ir-Ftog"
            }
          }
        }
      },
      "TokensResponse": {
        "content": {
          "application/json": {
            "example": {
              "acesssToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzE3NDNkYjg1Yzk2NDUzZTA0YTY4NCIsInNpZCI6IjY2NzE3OWE0YTgxZmI1MjIzOTg0NmY2MSIsImlhdCI6MTcxODcxMjc0MCwiZXhwIjoxNzE4NzE2MzQwfQ.hwdlZg0fft0PjwN63qwfjFTg1ZeyOOukFdZVbF0VOUU",
              "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NzE3NDNkYjg1Yzk2NDUzZTA0YTY4NCIsInNpZCI6IjY2NzE3OWE0YTgxZmI1MjIzOTg0NmY2MSIsImlhdCI6MTcxODcxMjc0MCwiZXhwIjoxNzE5MzE3NTQwfQ.B8htZY5kU0kvX2UYsEN0u7ZUPVxTKfCs5ASAocTc-P4"
            }
          }
        }
      },
      "UserResponse": {
        "content": {
          "application/json": {
            "example": {
              "id": "65c0388ea89738bb0120fed0",
              "name": "John Doe",
              "email": "user@example.com",
              "theme": "light",
              "avatar": "http://res.cloudinary.com/.../nsd6alpowmw3ska.jpg",
              "avatarPublicId": "TaskPro/user_avatars/jcczofobbijvvg066xjo"
            }
          }
        }
      },
      "UpdateOrderBadRequest": {
        "content": {
          "application/json": {
            "example": {
              "statusCode": 400,
              "message": {
                "ids": "Ids must be an array of valid ObjectIds"
              }
            }
          }
        }
      },
      "AllBoardsResponse": {
        "content": {
          "application/json": {
            "example": [
              {
                "title": "Project office",
                "icon": "project",
                "background": {
                  "identifier": "flowers",
                  "url": "https://res.cloudinary.com/dmbnnewoy/image/upload/v1707099093/TaskPro/board_bg_images/desk/nfxep55xgvpq7xitemq1.jpg",
                  "hasWhiteTextColor": true
                },
                "userId": "6671743db85c96453e04a684",
                "id": "6672f1d2f02c8b04130c718c"
              },
              {
                "title": "My office",
                "icon": "lightning",
                "background": {
                  "identifier": "blue-ball",
                  "url": "https://res.cloudinary.com/dmbnnewoy/image/upload/v1707099094/TaskPro/board_bg_images/desk/dtmqypo6r0v0nktpagku.jpg",
                  "hasWhiteTextColor": false
                },
                "userId": "6671743db85c96453e04a684",
                "id": "6672f211f02c8b04130c7193"
              }
            ]
          }
        }
      },
      "BoardResponse": {
        "content": {
          "application/json": {
            "example": {
              "background": {
                "identifier": "blue-ball",
                "url": "https://res.cloudinary.com/dmbnnewoy/image/upload/v1707099094/TaskPro/board_bg_images/desk/dtmqypo6r0v0nktpagku.jpg",
                "hasWhiteTextColor": false
              },
              "title": "My office",
              "icon": "lightning",
              "userId": "6671743db85c96453e04a684",
              "id": "6672f211f02c8b04130c7193"
            }
          }
        }
      },
      "BoardBadRequest": {
        "content": {
          "application/json": {
            "example": {
              "statusCode": 400,
              "message": {
                "title": "Title must be at least 3 characters",
                "icon": "Invalid enum value. Expected 'project' | 'star' | 'loading' | 'puzzle' | 'container' | 'lightning' | 'colors' | 'hexagon', received 'random-icon'"
              }
            }
          }
        }
      },
      "BoardByIdResponse": {
        "content": {
          "application/json": {
            "example": {
              "background": {
                "identifier": "flowers",
                "url": "https://res.cloudinary.com/dmbnnewoy/image/upload/v1707099093/TaskPro/board_bg_images/desk/nfxep55xgvpq7xitemq1.jpg",
                "hasWhiteTextColor": true
              },
              "id": "6672f1d2f02c8b04130c718c",
              "title": "Project office",
              "icon": "project",
              "userId": "6671743db85c96453e04a684",
              "columns": [
                {
                  "id": "6672f5cdc07147fc7ae1bb71",
                  "title": "To do",
                  "order": 0,
                  "boardId": "674345e37634766f05c4f7b1",
                  "cards": [
                    {
                      "id": "6672fda1c07147fc7ae1bb8a",
                      "title": "Research and Analysis",
                      "description": "Conduct in-depth research and analysis on the project's topic, gather relevant data, and identify key insights to inform decision-making and project planning.",
                      "priority": "Medium",
                      "deadline": "2025-10-20T00:00:00.000Z",
                      "order": 1,
                      "columnId": "6672f5cdc07147fc7ae1bb71"
                    }
                  ]
                },
                {
                  "id": "6672f5cdc07147fc7ae1bb71",
                  "title": "In progress",
                  "order": 1,
                  "boardId": "674345e37634766f05c4f7b1",
                  "cards": [
                    {
                      "id": "6672fdccc07147fc7ae1bb93",
                      "title": "Publication of the project",
                      "description": "Review the project materials: Familiarize yourself with the project's content, including text, images, and any supplementary materials.",
                      "priority": "High",
                      "deadline": "2025-10-15T00:00:00.000Z",
                      "order": 1,
                      "columnId": "6672f604c07147fc7ae1bb81"
                    }
                  ]
                }
              ]
            }
          }
        }
      },
      "ColumnResponse": {
        "content": {
          "application/json": {
            "example": {
              "id": "6672f604c07147fc7ae1bb81",
              "title": "In progress",
              "order": 1,
              "boardId": "67470718ed1b2ff3a2e5bd55"
            }
          }
        }
      },
      "ColumnBadRequest": {
        "content": {
          "application/json": {
            "example": {
              "statusCode": 400,
              "message": {
                "title": "Title must be at least 3 characters",
                "boardId": "Id must be a valid ObjectId"
              }
            }
          }
        }
      },
      "UpdateColumnsOrderResponse": {
        "content": {
          "application/json": {
            "example": [
              {
                "id": "67470731ed1b2ff3a2e5bd56",
                "title": "To do",
                "order": 0,
                "boardId": "67470718ed1b2ff3a2e5bd55"
              },
              {
                "id": "67470773c750b6298e1892ad",
                "title": "In progress",
                "order": 1,
                "boardId": "67470718ed1b2ff3a2e5bd55"
              },
              {
                "id": "67470737ed1b2ff3a2e5bd57",
                "title": "Done",
                "order": 2,
                "boardId": "67470718ed1b2ff3a2e5bd55"
              }
            ]
          }
        }
      },
      "CardResponse": {
        "content": {
          "application/json": {
            "example": {
              "id": "6672fdccc07147fc7ae1bb93",
              "title": "Publication of the project",
              "description": "Review the project materials: Familiarize yourself with the project's content, including text, images, and any supplementary materials.",
              "priority": "High",
              "deadline": "2025-10-15T00:00:00.000Z",
              "order": 1,
              "columnId": "6671743db85c96453e04a684"
            }
          }
        }
      },
      "CardBadRequest": {
        "content": {
          "application/json": {
            "example": {
              "statusCode": 400,
              "message": {
                "description": "Title must be a string",
                "priority": "Priority must be one of the following: Without, Low, Medium, High",
                "columnId": "Id must be a valid ObjectId"
              }
            }
          }
        }
      },
      "UpdateCardOrderResponse": {
        "content": {
          "application/json": {
            "example": [
              {
                "id": "6672fdccc07147fc7ae1bb93",
                "title": "Publication of the project",
                "description": "Review the project materials: Familiarize yourself with the project's content, including text, images, and any supplementary materials.",
                "priority": "High",
                "deadline": "2025-10-15T00:00:00.000Z",
                "order": 0,
                "columnId": "6671743db85c96453e04a684"
              },
              {
                "id": "6743474be4006eca6c8122e7",
                "title": "Publication of the project 2",
                "description": "Review the project materials: Familiarize yourself with the project's content, including text, images, and any supplementary materials.",
                "priority": "High",
                "deadline": "2025-10-15T00:00:00.000Z",
                "order": 1,
                "columnId": "6671743db85c96453e04a684"
              }
            ]
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": { "type": "http", "scheme": "bearer", "bearerFormat": "JWT" }
    }
  }
}
